const fs = require('fs');
const html = fs.readFileSync('D:/Admin/Documents/blog/resume-site/index.html', 'utf8');

// 1. Add tag bar in hero
const oldHero = '<p class="hero-desc reveal-item">从代码到产品，从传统SaaS到AI应用<br>用9年积累的全栈能力，做有结果的产品</p>\n            <div class="hero-cta reveal-item">';
const newHero = '<p class="hero-desc reveal-item">从代码到产品，从传统SaaS到AI应用<br>用9年积累的全栈能力，做有结果的产品</p>\n            <div class="hero-tags-bar">\n                <span class="tag-pill"><span class="tag-dot green"></span>党员</span>\n                <span class="tag-pill"><span class="tag-dot"></span>1988-12-27</span>\n                <span class="tag-pill"><span class="tag-dot"></span>本科在读</span>\n                <span class="tag-pill"><span class="tag-dot"></span>成都</span>\n            </div>\n            <div class="hero-cta reveal-item">';
let newHtml = html.replace(oldHero, newHero);

// 2. Replace about section
const start = newHtml.indexOf('<section class="section about-section" id="about">');
const end = newHtml.indexOf('</section>', start) + 10;
const newAbout = '<section class="section about-section" id="about">\n        <div class="container">\n            <div class="section-header"><span class="section-label">About</span><h2 class="section-title">关于我</h2></div>\n            <div class="about-grid">\n                <div class="about-text">\n                    <p class="about-lead">4年开发出身，深知代码实现逻辑，能与研发团队无障碍沟通，准确评估技术方案与工期。</p>\n                    <p>转型产品经理后，主导过移动APP、PC后台系统、SaaS平台、开放API等多种产品形态，覆盖B端SaaS、C端用户、电商、后台管理系统的完整产品闭环。具备从需求分析、PRD撰写、原型设计到迭代上线的全流程把控能力。</p>\n                    <p>近2年专注AI产品方向，自部署研究主流AI平台，探索AI Agent在工作流中的应用场景，正在将AI能力融入产品设计思维，寻求AI产品经理方向的新发展。</p>\n                    <div class="personal-info-row">\n                        <div class="pinfo-item"><span class="pinfo-label">出生年月</span><span class="pinfo-val">1988年12月27日</span></div>\n                        <div class="pinfo-item"><span class="pinfo-label">政治面貌</span><span class="pinfo-val">中共党员</span></div>\n                        <div class="pinfo-item"><span class="pinfo-label">学历</span><span class="pinfo-val">本科在读</span></div>\n                        <div class="pinfo-item"><span class="pinfo-label">现居地</span><span class="pinfo-val">成都</span></div>\n                        <div class="pinfo-item"><span class="pinfo-label">期望职位</span><span class="pinfo-val">中高级产品经理</span></div>\n                        <div class="pinfo-item"><span class="pinfo-label">期望薪资</span><span class="pinfo-val">15-20K</span></div>\n                    </div>\n                </div>\n                <div class="about-cards">\n                    <div class="about-card reveal-card"><div class="card-num">37</div><div class="card-label">岁</div></div>\n                    <div class="about-card reveal-card"><div class="card-num">5+</div><div class="card-label">年产品经验</div></div>\n                    <div class="about-card reveal-card"><div class="card-num">4</div><div class="card-label">年研发背景</div></div>\n                    <div class="about-card reveal-card"><div class="card-num">20+</div><div class="card-label">个版本迭代</div></div>\n                </div>\n            </div>\n        </div>\n    </section>';
newHtml = newHtml.substring(0, start) + newAbout + newHtml.substring(end);

fs.writeFileSync('D:/Admin/Documents/blog/resume-site/index.html', newHtml, 'utf8');
console.log('HTML updated');
